# Config
# ========================================================================================

# IMPORTANT: Set the URL of your site.
# Set to https://<username>.github.io when hosting on GitHub Pages
# (unless you are using a custom domain).
l:                   https://bititle:   thub.io

# IMPORTANT: Set The "base URL" of your site.
# When your site sits in a subdirectory, set to /<name of directory>
# (with leading /, but without the < >).
# Use the empty string '' otherwise.
# For GitHub project sites, this is usually the name of the project,
# e.g. `/hydejack`.
seurl:               ''

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                               H A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  ydejack Starter.
tagline:               >
  bigsweet's blog

#  Kit

# A shoe) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/icons/icon.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                <firstname> <lastname>
  email:               <mail@domain.tld>
  # Used by `jekyll-seo-tag`:
  # twitter:             <username>

# Add links to the sidebar.
menu:
  - title:             Example
    url:               /example/
  - title:             Blog
    url:               /Blog/
  - title:             Documenta# A sho short description (~s) o150 chaf thr# Config
# ========================================================================================

# IMPORTANT: Set the URL of your site.
# Set to https://<username>.github.io when hosting on GitHub Pages
# (unless you are using a custom domain).
url:                   https://big-sweet.github.io

# IMPORTANT: Set The "base URL" of your site.
# When your site sits in a subdirectory, set to /<name of directory>
# (with leading /, but without the < >).
# Use the empty string '' otherwise.
# For GitHub project sites, this is usually the name of the project,
# e.g. `/hydejack`.
baseurl:               ''

# Language of your content in 2-letter code, e.g.: en, de.
# You may also provide a location, e.g.: en-us, de_AT.
lang:                  en

# The title of your blog. Used in the sidebar and the browser tab.
title:                 bigsweet's blog

# A short description (~150 chars) of the page used for the meta description tag.
# Can use markdown, but no more than one paragraph (enforced by `>`)
description:           >
  bigsweet's blog

# A shorter description for the sidebar.
tagline:               >
  bigsweet's blog

# A list of keywords for your blog
keywords:              []

# A (square) logo for your site.
# If provided, it will be shown at the top of the sidebar.
# It also used by the `jekyll-seo-tag` plugin.
logo:                  /assets/icons/icon.png

# This should be the same author as first entry in `_data/authors.yml`.
author:
  name:                <firstname> <lastname>
  email:               <mail@domain.tld>
  # Used by `jekyll-seo-tag`:
  # twitter:             <username>

# Add links to the sidebar.
menu:
  - title:             Example
    url:               /example/
  - title:             Blog
    url:               /Blog/
  - title:             Documenta